"""update missions

Revision ID: 70413d65c518
Revises: 58e6078648c8
Create Date: 2025-09-05 04:10:36.905492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70413d65c518'
down_revision: Union[str, Sequence[str], None] = '58e6078648c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('TO_ORBIT', 'TO_EARTH', name='directionenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DELIVERED', 'CANCELLED', name='statusenum'), nullable=False),
    sa.Column('door_state', sa.Enum('OPEN', 'CLOSED', 'AJAR', name='doorstatesenum'), nullable=False),
    sa.Column('departure_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('arrival_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.add_column('cargos', sa.Column('mission_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cargos', 'missions', ['mission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cargos', type_='foreignkey')
    op.drop_column('cargos', 'mission_id')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_table('missions')
    # ### end Alembic commands ###
