"""mig1

Revision ID: 9ed0aa823d4f
Revises: fcdfdecdb8b8
Create Date: 2025-09-04 19:04:09.006357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed0aa823d4f'
down_revision: Union[str, Sequence[str], None] = 'fcdfdecdb8b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('cargo_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_slot_cargo_id'), 'slot', ['cargo_id'], unique=False)
    op.create_foreign_key(None, 'slot', 'cargos', ['cargo_id'], ['id'], ondelete='SET NULL')
    op.drop_column('slot', 'free')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('free', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'slot', type_='foreignkey')
    op.drop_index(op.f('ix_slot_cargo_id'), table_name='slot')
    op.drop_column('slot', 'cargo_id')
    # ### end Alembic commands ###
