"""rename some fields in Order model

Revision ID: c3b279461ce0
Revises: 10368c86165d
Create Date: 2025-09-04 12:15:35.393875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b279461ce0'
down_revision: Union[str, Sequence[str], None] = '10368c86165d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sender', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('phone_number', sa.String(), nullable=False))
    op.drop_column('orders', 'contact_phone')
    op.drop_column('orders', 'contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'phone_number')
    op.drop_column('orders', 'sender')
    # ### end Alembic commands ###
