"""init

Revision ID: fcdfdecdb8b8
Revises: 
Create Date: 2025-09-04 16:46:44.092746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcdfdecdb8b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('max_payload_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_lift_id'), 'lift', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('TO_ORBIT', 'TO_EARTH', name='directionenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DELIVERED', 'CANCELLED', name='statusenum'), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='sizeenum'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('position', sa.Enum('EARTH', 'ORBIT', name='positionenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DELIVERED', 'CANCELLED', name='statusenum'), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lift_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='slot_size'), nullable=False),
    sa.Column('free', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['lift_id'], ['lift.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_id'), 'slot', ['id'], unique=False)
    op.create_index(op.f('ix_slot_lift_id'), 'slot', ['lift_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_slot_lift_id'), table_name='slot')
    op.drop_index(op.f('ix_slot_id'), table_name='slot')
    op.drop_table('slot')
    op.drop_table('cargos')
    op.drop_table('roles')
    op.drop_table('orders')
    op.drop_index(op.f('ix_lift_id'), table_name='lift')
    op.drop_table('lift')
    # ### end Alembic commands ###
