"""create lift and slot

Revision ID: ffb1d921e139
Revises: c3b279461ce0
Create Date: 2025-09-04 08:28:01.214086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb1d921e139'
down_revision: Union[str, Sequence[str], None] = 'c3b279461ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sender', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('phone_number', sa.String(), nullable=False))
    op.drop_column('orders', 'contact_phone')
    op.drop_column('orders', 'contact')
    op.drop_constraint(op.f('slot_code_key'), 'slot', type_='unique')
    op.drop_column('slot', 'max_weight_kg')
    op.drop_column('slot', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot', sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('slot', sa.Column('max_weight_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('slot_code_key'), 'slot', ['code'], postgresql_nulls_not_distinct=False)
    op.add_column('orders', sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'phone_number')
    op.drop_column('orders', 'sender')
    # ### end Alembic commands ###
